### ISSUE TITLE
6.4 permissions 'identified by' mentioned every line.

### ISSUE THREAD

**Issue by grypyrg** [percona/training#7]
6.4 permissions 'identified by' mentioned every line.

this is redundant, should not happen. Only the first needs identified by.

**Comment by utdrmac** [comment]
Fixed. baaf0d2b10e0c5a570daed1592e43fe8aa82350d

**Comment by utdrmac** [comment]
Two of them needed it as there are two different users. Removed it from the 3rd GRANT.
