### ISSUE TITLE
What about using db1 and db2 as hostname.

### ISSUE THREAD

**Issue by grypyrg** [percona/training#8]
We should adjust the provisioning script to include the hostname in /etc/hosts by default.

So we can use the exercises to refer to db1 and db2, instead of ip addresses of db1-T\* and such. That' s more complex for students (I have to repeat this over and over again)

**Comment by utdrmac** [comment]
I usually do this manually. But agreed, it should be automated as part of the provisioning script. Hopefully puppet can take care of this.

```
./start-instances.php -a CONFIG -r us-west-1 -p FOO >foo_ssh_config.txt
./start-instances.php -a GENHOSTS -r us-west-1 -p FOO >foo_etc_hosts.txt
for i in `grep "Percona-Training-FOO-" foo_ssh_config.txt | awk '{print $2}'`; do 
  echo $i; cat foo_etc_hosts.txt | ssh -F foo_ssh_config.txt $i "cat - >>/etc/hosts";
done
```
